spring.application.name=safeguard-sa
#---server----
server.port=8080

# --- DEVELOPMENT DATABASE (H2) ---
spring.datasource.url=jdbc:h2:mem:safeguarddb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop


#--GEMINI AI(I am going to disable it for now ,M Kgomo will enable it)
#M Kgomo you wil add the actual values these are just dummies
# Google Gemini API (same for dev and prod \u2014 just set the env variable)
spring.ai.vertex.ai.gemini.project-id=safeguard-sa-placeholder
spring.ai.vertex.ai.gemini.location=us-central1
spring.ai.vertex.ai.gemini.api-key=${GEMINI_API_KEY}
spring.ai.vertex.ai.gemini.chat.model=gemini-1.5-flash
# Important: Temporarily disable chat until Member B sets their key [cite: 174]
spring.ai.vertex.ai.gemini.chat.enabled=false


# --- GMAIL SMTP SETTINGS ---
# For area alert notification emails [cite: 229]
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yourgmail@gmail.com
spring.mail.password=your_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

## Tell Thymeleaf exactly where the files are in the WAR structure
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false
