spring.application.name=safeguard-sa
# --- SERVER ---
server.port=8080

spring.config.import=optional:classpath:env.properties


spring.datasource.url=${SUPABASE_URL}
spring.datasource.username=postgres.wjgyvwwvdbwfehkjsbym
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true


spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.data-source-properties.sslmode=require

supabase.url=${SUPABASE_REST_URL}
supabase.api.key=${SUPABASE_ANON_KEY}

#AI
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
spring.ai.openai.chat.options.temperature=0.7

# --- Thymeleaf ---
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yourgmail@gmail.com
spring.mail.password=your_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true